// Pixel-art icons for the Design Lab components, 16×16.
// "#" outline (ink), "k" the component's colour, "s" a light highlight, "b" beige casing,
// "g" green screen, "." empty.
// toSvg() turns a map into a crisp inline SVG that follows the theme through CSS variables.

const maps = {
  client: [ // an old beige desktop: CRT monitor, floppy slot, keyboard
    "................",
    ".##############.",
    ".#bbbbbbbbbbbb#.",
    ".#b##########b#.",
    ".#b#gggggggg#b#.",
    ".#b#g##ggggg#b#.",
    ".#b#gggggggg#b#.",
    ".#b#g###gggg#b#.",
    ".#b##########b#.",
    ".#bbbbbbb###bb#.",
    ".##############.",
    "......####......",
    ".##############.",
    "#b#b#b#b#b#b#b##",
    "################",
    "................",
  ],
  dns: [ // globe
    ".......##.......",
    "..#########.....",
    "..#kkkkkkkk#....",
    "..#k#s#s#kkk#...",
    "..#kkkkkkkk#....",
    "..#########.....",
    ".......##.......",
    ".....#########..",
    "....#kkkkkkkk#..",
    "...#kkk#s#s#k#..",
    "....#kkkkkkkk#..",
    ".....#########..",
    ".......##.......",
    ".......##.......",
    ".....######.....",
    "................",
  ],
  cdn: [ // cloud
    "................",
    "................",
    "................",
    "......####......",
    "....##kkkk##....",
    "...#kkkkkkkk#...",
    "..#kkksskkkkk##.",
    ".##kkssskkkkkkk#",
    "#kkkkkkkkkkkkkk#",
    "#kkkkkkkkkkkkkk#",
    "#kkkkkkkkkkkkkk#",
    ".##############.",
    "................",
    "................",
    "................",
    "................",
  ],
  lb: [ // one in, three out
    "......####......",
    "......#kk#......",
    "......#kk#......",
    "......####......",
    ".......##.......",
    ".......##.......",
    "..############..",
    "..##....##....##",
    "..##....##....##",
    ".####..####..###",
    ".#kk#..#kk#..#k#",
    ".#kk#..#kk#..#k#",
    ".####..####..###",
    "................",
    "................",
    "................",
  ],
  gateway: [ // shield
    "..############..",
    "..#kkkkkkkkkk#..",
    "..#kkkkkkkkkk#..",
    "..#kkkk##kkkk#..",
    "..#kkk#ss#kkk#..",
    "..#kk#ssss#kk#..",
    "..#kkk#ss#kkk#..",
    "..#kkkk##kkkk#..",
    "..#kkkkkkkkkk#..",
    "...#kkkkkkkk#...",
    "....#kkkkkk#....",
    ".....#kkkk#.....",
    "......#kk#......",
    ".......##.......",
    "................",
    "................",
  ],
  ws: [ // lightning bolt
    ".........####...",
    "........#kkk#...",
    ".......#kkk#....",
    "......#kkk#.....",
    ".....#kkk#......",
    "....#kkkkk####..",
    "...#kkkkkkkkk#..",
    "...####kkkkk#...",
    "......#kkk#.....",
    ".....#kkk#......",
    "....#kkk#.......",
    "...#kkk#........",
    "...####.........",
    "................",
    "................",
    "................",
  ],
  app: [ // rack of servers with lights
    ".##############.",
    ".#kkkkkkkkkkkk#.",
    ".#ks.skkkk###k#.",
    ".#kkkkkkkkkkkk#.",
    ".##############.",
    ".#kkkkkkkkkkkk#.",
    ".#ks.skkkk###k#.",
    ".#kkkkkkkkkkkk#.",
    ".##############.",
    ".#kkkkkkkkkkkk#.",
    ".#ks.skkkk###k#.",
    ".#kkkkkkkkkkkk#.",
    ".##############.",
    "..##........##..",
    "................",
    "................",
  ],
  cache: [ // memory stick
    "................",
    "................",
    "................",
    "################",
    "#kkkkkkkkkkkkkk#",
    "#k###k###k###kk#",
    "#k#s#k#s#k#s#kk#",
    "#k###k###k###kk#",
    "#kkkkkkkkkkkkkk#",
    "######.#########",
    "#.#.#.#.#.#.#.#.",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  sql: [ // database cylinder with rows
    "....########....",
    "..##kkkkkkkk##..",
    ".#kkkkkkkkkkkk#.",
    ".##kkkkkkkkkk##.",
    ".#k##########k#.",
    ".#kkkkkkkkkkkk#.",
    ".##kkkkkkkkkk##.",
    ".#k##########k#.",
    ".#kkkkkkkkkkkk#.",
    ".##kkkkkkkkkk##.",
    ".#k##########k#.",
    ".#kkkkkkkkkkkk#.",
    "..##kkkkkkkk##..",
    "....########....",
    "................",
    "................",
  ],
  replica: [ // two small cylinders and a copy arrow
    "................",
    "......########..",
    ".....#kkkkkkkk#.",
    ".....##########.",
    ".....#kkkkkkkk#.",
    "..########kkkk#.",
    ".#kkkkkkkk#kkk#.",
    ".##########kkk#.",
    ".#kkkkkkkk#####.",
    ".#kkkkkkkk#.....",
    ".##########.....",
    ".#kkkkkkkk#.....",
    "..########......",
    "................",
    "................",
    "................",
  ],
  nosql: [ // cylinder split into columns (wide-column)
    "....########....",
    "..##kkkkkkkk##..",
    ".#kkkkkkkkkkkk#.",
    ".##kkkkkkkkkk##.",
    ".#k##k##k##k#k#.",
    ".#kk#kk#kk#kkk#.",
    ".#kk#kk#kk#kkk#.",
    ".#kk#kk#kk#kkk#.",
    ".#kk#kk#kk#kkk#.",
    ".#kk#kk#kk#kkk#.",
    ".#kk#kk#kk#kkk#.",
    ".#kkkkkkkkkkkk#.",
    "..##kkkkkkkk##..",
    "....########....",
    "................",
    "................",
  ],
  blob: [ // bucket
    "................",
    "..############..",
    ".#kkkkkkkkkkkk#.",
    ".##############.",
    ".#kkkkkkkkkkkk#.",
    "..#kkkkkkkkkk#..",
    "..#ksskkkkkkk#..",
    "..#kskkkkkkkk#..",
    "..#kkkkkkkkkk#..",
    "...#kkkkkkkk#...",
    "...#kkkkkkkk#...",
    "...#kkkkkkkk#...",
    "....########....",
    "................",
    "................",
    "................",
  ],
  queue: [ // messages lined up in a pipe
    "................",
    "................",
    "################",
    "................",
    ".###.###.###.###",
    ".#k#.#k#.#k#.#k#",
    ".#k#.#k#.#k#.#k#",
    ".###.###.###.###",
    "................",
    "################",
    "................",
    "............#...",
    "............##..",
    "##############..",
    "............##..",
    "............#...",
  ],
  worker: [ // gear
    "................",
    "......####......",
    "..##..#kk#..##..",
    "..#k###kk###k#..",
    "..##kkkkkkkk##..",
    "...#kkk##kkk#...",
    ".###kk#ss#kk###.",
    ".#kkk#ssss#kkk#.",
    ".#kkk#ssss#kkk#.",
    ".###kk#ss#kk###.",
    "...#kkk##kkk#...",
    "..##kkkkkkkk##..",
    "..#k###kk###k#..",
    "..##..#kk#..##..",
    "......####......",
    "................",
  ],
  idgen: [ // ticket with a hash sign
    "................",
    "................",
    "################",
    "#kkkkkkkkkkkkkk#",
    "#kk#k#kkkkkkkk.#",
    "#k#####kkkkkkk.#",
    "#kk#k#kkkkkkk..#",
    "#k#####kkkkkkk.#",
    "#kk#k#kkkkkkkk.#",
    "#kkkkkkkkkkkkkk#",
    "################",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  search: [ // magnifying glass
    "................",
    "....######......",
    "...#kkkkkk#.....",
    "..#kssskkkk#....",
    "..#kskkkkkk#....",
    "..#kkkkkkkk#....",
    "..#kkkkkkkk#....",
    "..#kkkkkkkk#....",
    "...#kkkkkk#.....",
    "....######.##...",
    "..........####..",
    "...........####.",
    "............####",
    ".............##.",
    "................",
    "................",
  ],
  geo: [ // map pin
    ".....######.....",
    "....#kkkkkk#....",
    "...#kkkkkkkk#...",
    "..#kkk####kkk#..",
    "..#kk#ssss#kk#..",
    "..#kk#ssss#kk#..",
    "..#kkk####kkk#..",
    "...#kkkkkkkk#...",
    "...#kkkkkkkk#...",
    "....#kkkkkk#....",
    ".....#kkkk#.....",
    "......#kk#......",
    ".......##.......",
    "....########....",
    "................",
    "................",
  ],
  push: [ // bell
    ".......##.......",
    "......####......",
    ".....#kkkk#.....",
    "....#kkkkkk#....",
    "....#ksskkk#....",
    "....#kskkkk#....",
    "....#kkkkkk#....",
    "...#kkkkkkkk#...",
    "...#kkkkkkkk#...",
    "..#kkkkkkkkkk#..",
    ".##############.",
    "................",
    "......####......",
    ".......##.......",
    "................",
    "................",
  ],
};

const FILL = { "#": "var(--icon-ink, currentColor)", k: "var(--k)", s: "var(--icon-lite, #fff)", b: "#d9cfae", g: "#9bbc0f" };

export function toSvg(rows) {
  const paths = { "#": "", k: "", s: "", b: "", g: "" };
  rows.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      let run = 1;
      while (x + run < row.length && row[x + run] === ch) run++;
      if (paths[ch] !== undefined) paths[ch] += `M${x} ${y}h${run}v1h-${run}z`;
      x += run;
    }
  });
  const body = Object.keys(paths).filter((c) => paths[c]).map((c) => `<path fill="${FILL[c]}" d="${paths[c]}"/>`).join("");
  return `<svg class="px-icon" viewBox="0 0 16 16" aria-hidden="true" shape-rendering="crispEdges">${body}</svg>`;
}

const icons = {};
for (const [k, rows] of Object.entries(maps)) {
  rows.forEach((r, i) => { if (r.length !== 16) throw new Error(`labIcons: ${k} row ${i} is ${r.length} wide`); });
  if (rows.length !== 16) throw new Error(`labIcons: ${k} has ${rows.length} rows`);
  icons[k] = toSvg(rows);
}
export default icons;
